In [12]:
## import
import pandas as pd
from pathlib import Path


import streamlit as st
import plotly.express as px
import plotly.graph_objects as go


TARGET_DIR = 'data'
TARGET_CSV = 'data.csv'

# BASE_DIR = Path(__file__).resolve().parent
BASE_DIR = Path.cwd().resolve().parent
DATA_PATH = BASE_DIR / TARGET_DIR / TARGET_CSV

## read_csv / file: "한국해양진흥공사_부산항_노선별_항만물류지표_KPLI.csv"
df = pd.read_csv(DATA_PATH)

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
0,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-05-28,23.69,644.50,0.00,7.94
1,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,22.01,608.54,0.00,16.20
2,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,16.52,749.45,0.00,1.36
3,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,22.37,634.28,0.00,7.44
4,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,16.37,654.99,0.00,1.80
...,...,...,...,...,...,...,...,...,...,...
475,KRPUS,부산항,VNSGN,호치민항,VN,2026-05-29,17.90,158.42,0.16,11.23
476,KRPUS,부산항,VNSGN,호치민항,VN,2026-06-15,17.12,216.15,0.18,31.91
477,KRPUS,부산항,VNSGN,호치민항,VN,2026-06-15,17.32,237.27,0.05,7.17
478,KRPUS,부산항,VNSGN,호치민항,VN,2026-06-15,18.19,232.12,0.02,22.30
479,KRPUS,부산항,VNSGN,호치민항,VN,2026-06-22,15.05,240.09,0.00,18.28

In [13]:
df.describe()

,항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
count,480.000000,480.000000,480.000000,480.000000
mean,19.756458,432.292521,0.138042,6.431250
std,5.754084,415.966180,0.269674,25.602098
min,6.950000,28.970000,0.000000,-322.050000
25%,16.350000,75.985000,0.000000,1.940000
50%,18.735000,327.210000,0.030000,7.645000
75%,21.427500,624.942500,0.170000,13.950000
max,47.010000,1632.540000,3.040000,135.920000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   출발항코드(DEPARTURE_PORT_CODE)  480 non-null    str
 1   출발항명(DEPARTURE_PORT_NAME)   480 non-null    str
 2   도착항코드(DEST_PORT_CODE)       480 non-null    str
 3   도착항명(DEST_PORT_NAME)        480 non-null    str
 4   도착항국가(DEST_COUNTRY)         426 non-null    str
 5   기준일자(DATE)                  480 non-null    str
 6   항만효율성(PORT_EFFICIENCY)      480 non-null    float64
 7   총항해시간(TOTAL_SAILING_TIME)   480 non-null    float64
 8   대기시간(WAITING_TIME)          480 non-null    float64
 9   항만정시성(ON_TIME_PERFORMANCE)  480 non-null    float64
dtypes: float64(4), str(6)
memory usage: 59.8 KB

In [17]:
df.columns.to_list()

['출발항코드(DEPARTURE_PORT_CODE)',
 '출발항명(DEPARTURE_PORT_NAME)',
 '도착항코드(DEST_PORT_CODE)',
 '도착항명(DEST_PORT_NAME)',
 '도착항국가(DEST_COUNTRY)',
 '기준일자(DATE)',
 '항만효율성(PORT_EFFICIENCY)',
 '총항해시간(TOTAL_SAILING_TIME)',
 '대기시간(WAITING_TIME)',
 '항만정시성(ON_TIME_PERFORMANCE)']

In [21]:
df[['항만효율성(PORT_EFFICIENCY)',
 '총항해시간(TOTAL_SAILING_TIME)',
 '대기시간(WAITING_TIME)',
 '항만정시성(ON_TIME_PERFORMANCE)']].isna().sum()

# 결측치는 존재하지않는다.

항만효율성(PORT_EFFICIENCY)        0
총항해시간(TOTAL_SAILING_TIME)     0
대기시간(WAITING_TIME)            0
항만정시성(ON_TIME_PERFORMANCE)    0
dtype: int64

In [52]:
dest_port_df = df[df['도착항코드(DEST_PORT_CODE)']!= 'KPLI']
kpli_port_df = df[df['도착항코드(DEST_PORT_CODE)']== 'KPLI']

dest_port_df['도착항코드(DEST_PORT_CODE)'].unique()
kpli_port_df['도착항코드(DEST_PORT_CODE)'].unique()
dest_port_df['기준일자(DATE)'].min(), dest_port_df['기준일자(DATE)'].max()
dest_port_df[['기준일자(DATE)','도착항코드(DEST_PORT_CODE)']].value_counts()
# kpli_port_df['기준일자(DATE)'].unique()

dest_port_df[
    (dest_port_df['기준일자(DATE)'] == '2025-10-15')
    &
    (dest_port_df['도착항코드(DEST_PORT_CODE)'] == 'AEJEA')
]
# 임의의 데이터를 추출해보니 동일일자 동일도착항의 데이터가 다름.

"""
 “월별 평균 KPI” 이 아니라
 “관측된 데이터 기준 월별 변화 추이”
"""
# df.groupby(['기준일자(DATE)', '도착항코드(DEST_PORT_CODE)']).size()

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
16,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-10-15,21.25,669.18,0.0,1.62
17,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-10-15,16.29,655.12,0.0,1.43
18,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-10-15,25.14,680.22,0.0,4.82
19,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-10-15,29.40,453.14,0.0,4.34